import initMenu from './modules/menu';
import initHeader from './modules/header';
import initClampFill from './modules/clamp-fill';
import initReveal from './modules/reveal';
import initAnchorScroll from './modules/anchor-scroll';
import initContactHighlight from './modules/contact-highlight';
import initForms from './modules/forms';
import initFileUpload from './modules/file-upload';
import initValidation from './modules/validation';
import initRte from './modules/rte';
import initSelect from './modules/select';

initReveal();
initMenu();
initHeader();
initClampFill();
initAnchorScroll();
initContactHighlight();
initSelect();
initRte();
initValidation();
initForms();
initFileUpload();
